#!/usr/bin/env bash

# Daemons
# Perhaps this sort of thing belongs elsewhere?
nm-applet &
emacs --daemon

setxkbmap -option grp:win_space_toggle -layout us,dk
xrdb -merge ~/.Xresources
acpid

# Nice for urxvt, not so nice for emacs:
# autocutsel -f

# From https://raw.githubusercontent.com/hemanth/haskell-rascal/master/imgs/swahili.png
hsetroot -center ~/.local/share/hsetroot/swahili.png
# xsettingsd &
compton -b
