#!/usr/bin/env bash

# Daemons
# Perhaps this sort of thing belongs elsewhere?
nm-applet &
# emacs --daemon

setxkbmap -option grp:win_space_toggle -layout us,dk
xrdb -merge $XDG_CONFIG_HOME/X11/Xresources
# This is now controlled from systemd - should consider using a proper
# session manager.
# acpid

# Nice for urxvt, not so nice for emacs:
# autocutsel -f

# From https://raw.githubusercontent.com/hemanth/haskell-rascal/master/imgs/swahili.png
hsetroot -center ~/.local/share/hsetroot/swahili.png
# xsettingsd &
compton -b
